data <- read.csv("household_power_consumption.txt",stringsAsFactors = FALSE,header = TRUE,sep = ";")
ftd <- strptime(paste(data$Date, data$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
data<-cbind(data,ftd)
data$Date <- as.Date(data$Date,format="%d/%m/%Y")
z<-which(data[,1]==as.Date('2007-02-01')|data[,1]==as.Date('2007-02-02'))
names<-colnames(data)
fdata<-data.frame(colnames(names))
fdata<-rbind(fdata,data[z,])
fdata$Global_active_power <- as.numeric(fdata$Global_active_power)
fdata$Global_reactive_power <- as.numeric(fdata$Global_reactive_power)
fdata$Voltage <- as.numeric(fdata$Voltage)
fdata$Global_intensity <- as.numeric(fdata$Global_intensity)
fdata$Sub_metering_1 <- as.numeric(fdata$Sub_metering_1)
fdata$Sub_metering_2 <- as.numeric(fdata$Sub_metering_2)
fdata$Sub_metering_3 <- as.numeric(fdata$Sub_metering_3)
png("plot2.png",width=480,height=480)
with(fdata, plot(ftd, Global_active_power, type="l", xlab="Day", ylab="Global Active Power (kilowatts)"))
dev.off()